### ISSUE TITLE
authenticate_userの例外処理

### ISSUE THREAD

**Issue by benrickken** [benrickken/crowdfunding-frontend#61]
https://github.com/benrickken/crowdfunding-api/pull/24#discussion_r640251547

> なるほど。ログインできてないなら renderして終わる、流れですね。これもシンプルでアリですね。
> 
> 今後サービスが複雑になってくる事が予想される場合、以下のような形を考えそうです。
> 
> current_userは情報が取れない場合には例外を投げる（丁寧にやるなら例外クラスも作る）
> デフォルトの実装はApplicationControllerで rescue_fromしてjsonをrenderする
> こうしておくと「ある場合にはログインしていなくてもエラーにしない」ような実装にも変更しやすい（begin-rescueするとか、子Controllerでrescue_fromするとかできる）ので変更に強いと考えます。rambulanceみたいなエラーハンドリングのgemとも相性が良い（今回はAPIサーバーなのでここまで考えずとも良いかもですが）です。

**Comment by ms2sato** [comment]
@benrickken 実際に進めるときには、一度どう作るか一緒に検討しましょう。パターンはいくつか考えられると思います。

**Comment by benrickken** [comment]
TODO
* デフォルトの実装はApplicationControllerで rescue_fromしてjsonをrenderする
  * StandardErrorを拾って500を返す
* UnauthenticatedError的な例外処理を作ってauthenticate_user!でraiseする
